### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/pony#89]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/pony/issues/80)
- [x] [Add key features](https://github.com/exercism/pony/issues/81)
- [x] [Add tags](https://github.com/exercism/pony/issues/82)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/pony/issues/83)
- [x] [Update status of track](https://github.com/exercism/pony/issues/87)
- [x] [Update status of Concept Exercises](https://github.com/exercism/pony/issues/88)
- [x] [Pass linting checks](https://github.com/exercism/pony/issues/84)
- [x] [Build Test Runner](https://github.com/exercism/pony/issues/85)
- [x] [Build Analyzer and Representer](https://github.com/exercism/pony/issues/86) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by redvers** [comment]
Completed by https://github.com/exercism/pony-test-runner/pull/2
